# Generated by Django 6.0.2 on 2026-05-31 14:31

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_body',
            field=tinymce.models.HTMLField(max_length=2000),
        ),
    ]
