# Generated by Django 6.0.2 on 2026-02-15 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_heading', models.TextField(max_length=50)),
                ('about_text', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'About',
            },
        ),
    ]
