# Generated by Django 6.0.2 on 2026-02-15 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='about_heading',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='about',
            name='about_text',
            field=models.TextField(max_length=255),
        ),
    ]
